function h = fix_axis(h)
% function h = set_rev_axis(h)
% Filip Szczepankiewicz
% Axis configuration used in review paper 2021.

if nargin < 1
    h = gca;
end

set(...
    h, ...
    'TickDir', 'out', ...
    'TickLength', [1 1]*0.01, ...
    'Box', 'off', ...
    'LineWidth', 0.6, ...
    'FontWeight', 'normal', ...
    'fontname', 'times',...
    'layer', 'top'...
);

h.FontSize = 10;

h.TitleFontSizeMultiplier = 1.1;
h.TitleFontWeight = 'normal';